### ISSUE TITLE
My scenario can't run because injects stay in pending but it's executed

### ISSUE THREAD

**Issue by Seb-MIGUEL** [OpenAEV-Platform/openaev#3550]
As you can see here sometimes into my scenario injects are successfully done but still pending and when I've got chaining that blocked my scenario

**Comment by impolitepanda** [comment]
After debugging with Damien, and discussing with Gael, here is the root cause of the issue: 
When launching an inject targeting a crowdstrike agent on an asset, the full list of calls to the crowdstrike API and then the updating of the inject's status in our database to EXECUTING could take longer than the time it took the implant to execute the payload and then set the inject's status to SUCCESS or ERROR. 
This means that the SUCCESS or ERROR status is then overriden by the previous but too long call to update it to EXECUTING, thus creating this issue.

Quick fix : check in the api that the statuses are correct when the implant calls the callback function, and reply for a 409 if not. The implant will then retry. This simulates a sleep call, without triggering any side effect that a cleaner solution could create.

**Comment by impolitepanda** [comment]
The issue seems to reoccur sometimes. As such we have increased the number of retries from 5 to 20 (resulting from increasing from 5 seconds to 20 seconds before reconciliation). This is a work around to help us debug the issue further.

**Comment by impolitepanda** [comment]
To add context: there was a concurrency issued where tow or more implants could send "completed" execution trace at the same time, thus failing to set the global inject status to executed.
We implemented a lock/semaphor mechanism to fix this problem.

**Comment by antoinemzs** [comment]
I think this is back occurring with the introduction of the batching feature, the trace processing is a bit too fragile for dealing with batching

Example runs with batching (simulations are still "ongoing") and without, i.e. "legacy" trace handling (simualtions are "finished")

<img width="1647" height="1083" alt="Image" src="https://github.com/user-attachments/assets/c2e4cd1e-209b-42d8-9480-2c41c391aa29" />

**Comment by DeniseMonreale** [comment]
Tested on [testing ](https://testing.obas.staging.filigran.io/admin/atomic_testings/e018b22d-d051-4a0c-8663-87b62fd89083?query=cGFnZT0wJnNpemU9MjAmZmlsdGVyR3JvdXBbZmlsdGVyc11bXSZmaWx0ZXJHcm91cCU1Qm1vZGUlNUQ9YW5kJmtleT1BU1NFVFNfZTAxOGIyMmQtZDA1MS00YTBjLTg2NjMtODdiNjJmZDg5MDgzX2ZpbHRlcnM%3D)

still have problem and some target are not even started @impolitepanda @damgouj

**Comment by antoinemzs** [comment]
> Tested on [testing ](https://testing.obas.staging.filigran.io/admin/atomic_testings/e018b22d-d051-4a0c-8663-87b62fd89083?query=cGFnZT0wJnNpemU9MjAmZmlsdGVyR3JvdXBbZmlsdGVyc11bXSZmaWx0ZXJHcm91cCU1Qm1vZGUlNUQ9YW5kJmtleT1BU1NFVFNfZTAxOGIyMmQtZDA1MS00YTBjLTg2NjMtODdiNjJmZDg5MDgzX2ZpbHRlcnM%3D)
> 
> still have problem and some target are not even started [@impolitepanda](https://github.com/impolitepanda) [@damgouj](https://github.com/damgouj)

We haven't looked in full depth yet, but there are signs that the test infrastructure might also be failing (e.g. broken machines)

**Comment by RomuDeuxfois** [comment]
@antoinemzs , @damgouj , @impolitepanda what's the status of this issue ?

**Comment by damgouj** [comment]
> [@antoinemzs](https://github.com/antoinemzs) , [@damgouj](https://github.com/damgouj) , [@impolitepanda](https://github.com/impolitepanda) what's the status of this issue ?

For me, it's OK on testing but maybe @antoinemzs has some insight ?

**Comment by antoinemzs** [comment]
There was a missing link to #5408
